import {test,expect,type APIRequestContext} from '@playwright/test';
import {demoQuestionnaire} from '../../packages/domain';
import {PRODUCTS} from '../../packages/jurisdiction-engine/catalog';
const headers={Origin:'http://127.0.0.1:3000'};
async function post(request:APIRequestContext,action:string,data:unknown={}){const r=await request.post(`/api/${action}`,{headers,data});expect(r.ok(),`${action}: ${await r.text()}`).toBeTruthy();return r.json();}
test('customer browser journey: signup, questionnaire, recommendations, mock checkout and private documents',async({page})=>{
 const consoleErrors:string[]=[];page.on('pageerror',e=>consoleErrors.push(e.message));
 await page.goto('/registro');await page.getByLabel('Tu nombre').fill('Mariana QA');await page.getByLabel('Correo electrónico').fill(`mariana-${Date.now()}@example.test`);await page.getByLabel('Contraseña',{exact:true}).fill('Sandbox-password-2026');await page.getByRole('button',{name:'Crear cuenta',exact:true}).click();await expect(page).toHaveURL('/panel');await expect(page.getByText('El próximo capítulo empieza aquí.')).toBeVisible();
 await page.getByRole('link',{name:'Construir mi ruta',exact:true}).click();await page.getByLabel('Nombre legal',{exact:true}).fill('Mariana');await page.getByLabel('Apellido legal').fill('Prueba');await page.getByLabel('Fecha de nacimiento').fill('1990-01-01');await page.getByRole('button',{name:'Continuar',exact:true}).click();
 await page.getByLabel('Nombre propuesto').fill('Andes QA Studio');await page.getByLabel('¿A qué se dedica tu negocio?').fill('Desarrollo de software para empresas internacionales');await page.getByRole('button',{name:'Continuar',exact:true}).click();await page.getByRole('checkbox',{name:/Acepto el/}).check();await page.getByRole('button',{name:'Ver mis recomendaciones'}).click();await expect(page).toHaveURL(/\/recomendaciones\//);await expect(page.locator('.recommendation')).toHaveCount(4);
 await page.locator('.recommendation').filter({has:page.getByRole('heading',{name:'Wyoming LLC',exact:true})}).getByRole('button',{name:'Preparar esta ruta'}).click();await expect(page).toHaveURL(/\/casos\//);await page.getByRole('button',{name:'Revisar orden'}).click();await expect(page).toHaveURL(/\/checkout\//);await expect(page.getByText('CHECKOUT SANDBOX',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Confirmar pago simulado'}).click();await expect(page).toHaveURL(/\/casos\//);await expect(page.getByText('Esperando al responsable')).toBeVisible();
 await page.goto('/documentos');await page.getByLabel('Seleccionar archivo').setInputFiles({name:'test.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.7\nSynthetic QA fixture only\n%%EOF')});await page.getByRole('button',{name:'Subir documento',exact:true}).click();await expect(page.getByText('test.pdf',{exact:true})).toBeVisible();await expect(page.getByText('En revisión',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Descargar'})).toBeDisabled();
 await page.screenshot({path:'.local/qa/documents-desktop.png',fullPage:true});expect(consoleErrors).toEqual([]);
});
test('all four backend journeys, tenant isolation, operator workflow, calendar and reminder',async({playwright})=>{
 const customer=await playwright.request.newContext({baseURL:'http://127.0.0.1:3000'});const stranger=await playwright.request.newContext({baseURL:'http://127.0.0.1:3000'});const admin=await playwright.request.newContext({baseURL:'http://127.0.0.1:3000'});
 await post(customer,'signup',{email:`journey-${Date.now()}@example.test`,password:'Sandbox-password-2026',displayName:'Journey'});await post(stranger,'signup',{email:`stranger-${Date.now()}@example.test`,password:'Sandbox-password-2026',displayName:'Other tenant'});await post(admin,'sandbox-ops');
 const onboarding=await post(customer,'onboard',{questionnaire:demoQuestionnaire,founder:{legalFirstName:'Test',legalLastName:'Founder',dateOfBirth:'1990-01-01',nationality:'MX',residence:'MX',taxResidences:['MX']}});
 for(const j of Object.keys(PRODUCTS) as (keyof typeof PRODUCTS)[]){const c=await post(customer,'case-create',{businessId:onboarding.businessId,jurisdiction:j});const denied=await stranger.post('/api/checkout-create',{headers,data:{caseId:c.id}});expect(denied.status()).toBe(404);await post(customer,'checkout-create',{caseId:c.id});const workspace=await(await customer.get('/api/workspace')).json();const order=workspace.records.orders.find((o:{formation_case_id:string})=>o.formation_case_id===c.id);await post(customer,'checkout-mock',{orderId:order.id});for(const step of PRODUCTS[j].workflow)await post(admin,'case-advance',{caseId:c.id,stepCode:step.code,confirmed:true,mock:true,reference:'E2E-verified-simulation'});}
 const result=await(await customer.get('/api/workspace')).json();expect(result.records.companies).toHaveLength(4);expect(result.records.company_obligations.length).toBeGreaterThanOrEqual(6);expect(result.records.formation_cases.every((c:{status:string})=>c.status==='ACTIVE_COMPLIANCE')).toBe(true);const other=await(await stranger.get('/api/workspace')).json();expect(other.records.companies).toHaveLength(0);expect(other.records.formation_cases).toHaveLength(0);const calendar=await customer.get('/api/calendar');expect(await calendar.text()).toContain('BEGIN:VEVENT');const due=result.records.company_obligations.find((o:{due_at:string|null})=>o.due_at).due_at;const reminderDate=new Date(due);reminderDate.setUTCDate(reminderDate.getUTCDate()-30);const notified=await post(admin,'notify',{today:reminderDate.toISOString().slice(0,10)});expect(notified.created).toBeGreaterThan(0);expect((await post(admin,'notify',{today:reminderDate.toISOString().slice(0,10)})).created).toBe(0);await post(customer,'subscription-create',{companyId:result.records.companies[0].id});
 await customer.dispose();await stranger.dispose();await admin.dispose();
});
test('public routes and mobile layout remain usable',async({page})=>{for(const route of ['/','/comparar','/como-funciona','/precios','/cumplimiento','/delaware','/wyoming','/estonia','/reino-unido','/privacidad','/terminos','/alcance']){const r=await page.goto(route);expect(r?.status()).toBe(200);await expect(page.locator('main')).toBeVisible();}await page.setViewportSize({width:390,height:844});await page.goto('/');await expect(page.getByRole('heading',{level:1})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:'.local/qa/home-mobile.png',fullPage:true});await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'.local/qa/home-desktop.png',fullPage:true});});
test('anonymous, CSRF, forged webhook and role-change attempts are denied',async({request})=>{expect((await request.get('/api/workspace')).status()).toBe(401);expect((await request.post('/api/signup',{data:{},headers:{Origin:'https://evil.example'}})).status()).toBe(403);expect((await request.post('/api/stripe-webhook',{data:{type:'checkout.session.completed'}})).status()).toBe(400);});
test('admin evidence editor, document approval, protected download and mobile panel',async({page,playwright})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await post(page.request,'sandbox-ops');await page.goto('/admin');await page.getByRole('tab',{name:'reglas',exact:true}).click();await expect(page.locator('.rule-grid article').first()).toBeVisible();await page.getByText('Preparar nueva versión y evidencia',{exact:true}).first().click();await expect(page.getByLabel('Resultado estructurado (JSON)').first()).toBeVisible();await page.screenshot({path:'.local/qa/admin-rules.png',fullPage:false});
 const customer=await playwright.request.newContext({baseURL:'http://127.0.0.1:3000'});await post(customer,'signup',{email:`document-${Date.now()}@example.test`,password:'Sandbox-password-2026',displayName:'Document QA'});const business=await post(customer,'onboard',{questionnaire:demoQuestionnaire,founder:{legalFirstName:'Test',legalLastName:'Founder',dateOfBirth:'1990-01-01',nationality:'MX',residence:'MX',taxResidences:['MX']}});const c=await post(customer,'case-create',{businessId:business.businessId,jurisdiction:'GB'});
 const bytes=Buffer.from('%PDF-1.7\nPrivate synthetic document\n%%EOF');const uploaded=await customer.post('/api/upload',{headers,multipart:{caseId:c.id,file:{name:'private.pdf',mimeType:'application/pdf',buffer:bytes}}});expect(uploaded.ok()).toBe(true);const{id}=await uploaded.json();expect((await customer.post('/api/document-link',{headers,data:{id}})).status()).toBe(409);await post(page.request,'document-review',{id,approve:true});const{url}=await post(customer,'document-link',{id});expect(await(await customer.get(url)).body()).toEqual(bytes);
 const anonymous=await playwright.request.newContext({baseURL:'http://127.0.0.1:3000'});expect((await anonymous.get(url)).status()).toBe(401);await anonymous.dispose();await customer.dispose();await page.setViewportSize({width:390,height:844});await page.goto('/panel');await expect(page.locator('.stats-grid')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.getByRole('button',{name:'Abrir menú'}).click();await expect(page.getByRole('navigation',{name:'Navegación principal'})).toBeVisible();await expect.poll(async()=>Math.round((await page.locator('aside.sidebar').boundingBox())!.x)).toBe(0);await page.screenshot({path:'.local/qa/panel-mobile.png',fullPage:false});expect(errors).toEqual([]);
});
