'use client';
import {useRouter} from 'next/navigation';
import { useState,useEffect } from 'react';
import Link from 'next/link';
import { ArrowRight,Check,AlertTriangle } from 'lucide-react';
import type { Recommendation } from '../../../../packages/jurisdiction-engine';
import { PRODUCTS } from '../../../../packages/jurisdiction-engine/catalog';
import { api,Action,Badge,Evidence,money } from '../../components/ui';
export function Recommendations({businessId}:{businessId?:string}){const router=useRouter();const[items,setItems]=useState<Recommendation[]>([]);const[error,setError]=useState('');useEffect(()=>{if(!businessId)return;let active=true;fetch(`/api/recommendations?businessId=${businessId}`).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);if(active)setItems(d);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[businessId]);
 if(!businessId)return <div className="empty-state"><h2>Primero, tu contexto.</h2><p>Completa la evaluación para comparar las cuatro rutas.</p><Link className="btn" href="/iniciar">Empezar evaluación</Link></div>;
 return <>{error&&<p role="alert" className="error-text">{error}</p>}<div className="notice"><AlertTriangle size={18}/><p>El puntaje mide afinidad con tu perfil, no garantiza elegibilidad ni aprobación. La actividad, identidad y titularidad requieren validación.</p></div>{items.length===0&&!error&&<p role="status">Revisando tu contexto…</p>}<div className="recommendation-grid">{items.map((r,i)=><article className={`card recommendation ${i===0?'highlight':''}`} key={r.jurisdiction}><div className="card-heading"><span className="country-code">{r.jurisdiction}</span><Badge tone={r.eligibility==='review_required'?'amber':'blue'}>{r.eligibility==='review_required'?'Revisión requerida':'Posible, sujeto a revisión'}</Badge></div><div className="recommendation-title"><h2>{PRODUCTS[r.jurisdiction].name}</h2><div className="score">{r.score}<small>/100 afinidad</small></div></div><div className="score-track"><span style={{width:`${r.score}%`}}/></div><ul className="benefit-list">{r.reasons_for.map(s=><li key={s}><Check size={15}/>{s}</li>)}</ul>{r.reasons_against.map(s=><p className="warning-text" key={s}>{s}</p>)}<h4>Costo gubernamental</h4>{r.government_fees.map(f=><div className="cost-line" key={f.title}><span>{f.title}</span><b>{money(f.amountMinor,f.currency)}</b></div>)}<p className="fine-print">Tarifa de plataforma y servicios de partners por separado.</p><h4>Antes de presentar</h4><ul>{r.prerequisites.map(s=><li key={s}>{s}</li>)}</ul><h4>Servicios a coordinar</h4><ul>{r.mandatory_partner_services.map(s=><li key={s}>{s}</li>)}</ul><details className="recommendation-details"><summary>Obligaciones, advertencias y evidencia</summary><h4>Después de constituir</h4>{r.annual_obligations.map(s=><p key={s}>{s}</p>)}{r.warnings.map(s=><p className="warning-text" key={s}>{s}</p>)}<Evidence facts={r.sources}/></details><Action className={i===0?'full':'full secondary'} onAction={async()=>{const result=await api<{id:string}>('case-create',{businessId,jurisdiction:r.jurisdiction});router.push(`/casos/${result.id}`);}}>Preparar esta ruta <ArrowRight size={16}/></Action></article>)}</div></>;
}

