import {expect,test} from 'vitest';
import {readFile} from 'node:fs/promises';
import {testDatabase} from './harness';
import {LocalRepository} from '../../packages/persistence';
import {Application,type Actor} from '../../packages/application';
import {demoQuestionnaire} from '../../packages/domain';
import {confirmDelawarePatch,getDelawareConversation,sendDelawareMessage,startDelawareConversation} from '../../packages/onboarding-agent/service';

test('Delaware conversation is tenant-bound, confirm-first and leaves filing, payment and case state untouched',async()=>{
 const db=await testDatabase();try{await db.exec(await readFile('supabase/seed.sql','utf8'));const repo=new LocalRepository(db);const user='00000000-0000-4000-8000-000000000093';await db.query('insert into auth.users(id) values($1)',[user]);const actor={id:user,organizationId:String((await repo.list('organization_members',{user_id:user}))[0].organization_id),role:'customer',displayName:'Delaware QA'} as Actor;const app=new Application(repo,true);const onboarded=await app.onboard(actor,demoQuestionnaire,{firstName:'Test',lastName:'Founder',dateOfBirth:'1990-01-01'});const created=await app.createCase(actor,onboarded.businessId,'US-DE');const original=JSON.stringify((await repo.list('formation_cases',{id:created.id}))[0]);const started=await startDelawareConversation(repo,actor,true,{caseId:created.id,caseRevision:0,synthetic:true,clientRequestId:'20000000-0000-4000-8000-000000000001'});expect(started.conversation).toMatchObject({jurisdiction:'US-DE',revision:0,status:'active'});expect(Object.keys(started.conversation.state)).toHaveLength(20);
 const sent=await sendDelawareMessage(repo,actor,true,{conversationId:started.conversation.id,revision:0,message:'Nombre propuesto: Orbit Delaware QA LLC',clientRequestId:'20000000-0000-4000-8000-000000000002'});expect(sent.conversation.state.companyName).toBe('');expect(sent.conversation.pendingPatch).toEqual({companyName:'Orbit Delaware QA LLC'});const confirmed=await confirmDelawarePatch(repo,actor,true,{conversationId:started.conversation.id,revision:1,accept:true,clientRequestId:'20000000-0000-4000-8000-000000000003'});expect(confirmed.conversation.state.companyName).toBe('Orbit Delaware QA LLC');expect((await getDelawareConversation(repo,actor,true,created.id))?.conversation.state.companyName).toBe('Orbit Delaware QA LLC');expect(JSON.stringify((await repo.list('formation_cases',{id:created.id}))[0])).toBe(original);expect(await repo.list('orders')).toHaveLength(0);expect(await repo.list('companies')).toHaveLength(0);expect(await repo.list('company_registrations')).toHaveLength(0);const events=await repo.list('case_events',{case_id:created.id});expect(JSON.stringify(events)).not.toContain('Orbit Delaware QA LLC');
 }finally{await db.close();}
});
