'use client';
import {useRouter} from 'next/navigation';
import { useState,type FormEvent } from 'react';
import { ArrowLeft,ArrowRight,Check,ShieldCheck } from 'lucide-react';
import { demoQuestionnaire,type Questionnaire } from '../../../../packages/domain';
import { api } from '../../components/ui';
const countries=(value:string)=>value.split(',').map(s=>s.trim().toUpperCase()).filter(Boolean);
export function QualificationWizard(){const router=useRouter();const[step,setStep]=useState(0);const[q,setQ]=useState<Questionnaire>({...demoQuestionnaire,proposedName:'',activity:''});const[founder,setFounder]=useState({legalFirstName:'',legalLastName:'',dateOfBirth:''});const[consent,setConsent]=useState(false);const[error,setError]=useState('');const[busy,setBusy]=useState(false);
 const field=<K extends keyof Questionnaire>(key:K,value:Questionnaire[K])=>setQ({...q,[key]:value});
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError('');if(step<2){setStep(step+1);return;}if(!consent){setError('Confirma el alcance y el uso de tus datos.');return;}setBusy(true);try{const result=await api<{businessId:string}>('onboard',{questionnaire:q,founder:{...founder,nationality:q.nationality,residence:q.residence,taxResidences:q.taxResidences}});router.push(`/recomendaciones/${result.businessId}`);}catch(e){setError(e instanceof Error?e.message:'Revisa la información');}finally{setBusy(false);}}
 const toggle=(key:keyof Questionnaire,label:string,description?:string)=><label className="toggle-row" key={key}><span><b>{label}</b>{description&&<small>{description}</small>}</span><input type="checkbox" checked={q[key]===true} onChange={e=>field(key,e.target.checked)}/></label>;
 return <div className="wizard-layout"><aside className="wizard-guide"><span className="eyebrow">TU PUNTO DE PARTIDA</span><h2>Primero tú.<br/>Luego, tu ruta.</h2><p>Necesitamos entender tu contexto para comparar opciones de forma responsable.</p><ol>{['Sobre ti','Tu negocio','Planes y requisitos'].map((label,i)=><li key={label} className={i===step?'current':i<step?'done':''}><span>{i<step?<Check size={14}/>:i+1}</span>{label}</li>)}</ol><div className="notice"><ShieldCheck size={18}/><p>No determines tu residencia fiscal únicamente por dónde constituyes una empresa.</p></div></aside><form className="wizard-form card" onSubmit={submit}><div className="card-heading"><span className="eyebrow">PASO {step+1} DE 3</span><span className="muted">La información se guarda al finalizar</span></div>
 {step===0&&<><h2>Conozcámonos un poco.</h2><p>Indica tu información personal y los países relevantes para ti.</p><div className="form-grid"><label>Nombre legal<input required value={founder.legalFirstName} onChange={e=>setFounder({...founder,legalFirstName:e.target.value})} maxLength={100}/></label><label>Apellido legal<input required value={founder.legalLastName} onChange={e=>setFounder({...founder,legalLastName:e.target.value})} maxLength={100}/></label><label>Fecha de nacimiento<input type="date" required value={founder.dateOfBirth} onChange={e=>setFounder({...founder,dateOfBirth:e.target.value})}/></label><label>Nacionalidad (código ISO)<input required pattern="[A-Z]{2}" maxLength={2} value={q.nationality} onChange={e=>field('nationality',e.target.value.toUpperCase())}/><small>Ejemplo: MX, CO, AR, CL, US.</small></label><label>País de residencia<input required pattern="[A-Z]{2}" maxLength={2} value={q.residence} onChange={e=>field('residence',e.target.value.toUpperCase())}/></label><label>Residencias fiscales<input required defaultValue={q.taxResidences.join(', ')} onBlur={e=>field('taxResidences',countries(e.target.value))}/><small>Códigos ISO separados por coma.</small></label></div></>}
 {step===1&&<><h2>Dale contexto a tu idea.</h2><p>La actividad y la estructura importan más que una etiqueta.</p><label>Nombre propuesto<input required minLength={2} maxLength={120} value={q.proposedName} onChange={e=>field('proposedName',e.target.value)} placeholder="El nombre que tienes en mente"/></label><label>¿A qué se dedica tu negocio?<textarea required minLength={10} maxLength={2000} value={q.activity} onChange={e=>field('activity',e.target.value)} placeholder="Describe qué ofreces, a quién y cómo operas." rows={3}/></label><div className="form-grid"><label>Número de fundadores<input required type="number" min={1} max={100} value={q.founderCount} onChange={e=>field('founderCount',Number(e.target.value))}/></label><label>Tu porcentaje de propiedad<input required type="number" min={0} max={100} value={q.ownershipPercent} onChange={e=>field('ownershipPercent',Number(e.target.value))}/></label><label>Ingresos anuales estimados<input required type="number" min={0} step="0.01" value={q.expectedRevenueMinor/100} onChange={e=>field('expectedRevenueMinor',Math.round(Number(e.target.value)*100))}/></label><label>Moneda<select value={q.currency} onChange={e=>field('currency',e.target.value as Questionnaire['currency'])}><option>USD</option><option>EUR</option><option>GBP</option></select></label><label>Países de tus clientes<input required defaultValue={q.customerCountries.join(', ')} onBlur={e=>field('customerCountries',countries(e.target.value))}/></label><label>Países donde operas<input required defaultValue={q.operatingCountries.join(', ')} onBlur={e=>field('operatingCountries',countries(e.target.value))}/></label></div>{q.founderCount>1&&<div className="notice amber">La estructura de varios propietarios requiere revisión y completar a los demás titulares antes de presentar.</div>}</>}
 {step===2&&<><h2>Hablemos de tus planes.</h2><p>Estas señales nos ayudan a identificar requisitos y revisiones.</p><div className="toggle-grid">{toggle('hasEmployees','Tendré empleados')}{toggle('plansFundraising','Buscaré inversión')}{toggle('requiresUsd','Necesito operar en USD')}{toggle('requiresEur','Necesito operar en EUR')}{toggle('needsStripe','Me interesa usar Stripe')}{toggle('physicalOffice','Tendré oficina física')}{toggle('inventory','Manejaré inventario')}{toggle('crypto','Hay exposición a cripto')}{toggle('regulated','Mi actividad está regulada')}{toggle('foreignOwnedDisregarded','LLC unipersonal de propiedad extranjera','Señal para revisión de clasificación fiscal')}</div><h3>Requisitos de las rutas</h3><div className="toggle-grid">{toggle('eResident','Ya tengo e-Residency')}{toggle('boardInEstonia','La junta operará desde Estonia')}{toggle('legalAddressInEstonia','El domicilio legal estará en Estonia')}{toggle('directorsVerified','Directores verificados en Companies House','Declaración inicial; se pedirá evidencia')}{toggle('pscVerified','PSC verificados','Las declaraciones PSC se revisan por separado')}</div><label>Activos ubicados y utilizados en Wyoming (USD)<input type="number" min={0} step="0.01" value={q.wyomingAssetsMinor/100} onChange={e=>field('wyomingAssetsMinor',Math.round(Number(e.target.value)*100))}/></label><label className="consent-row"><input type="checkbox" required checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>Acepto el <a href="/alcance" target="_blank">alcance del servicio</a> y la <a href="/privacidad" target="_blank">privacidad</a>. Entiendo que esta evaluación no garantiza aprobación ni resultados fiscales.</span></label></>}
 {error&&<div role="alert" className="notice error-text">{error}</div>}<div className="wizard-actions">{step>0?<button type="button" className="btn ghost" onClick={()=>setStep(step-1)}><ArrowLeft size={16}/> Anterior</button>:<span/>}<button className="btn" disabled={busy}>{busy?'Preparando tu evaluación…':step===2?'Ver mis recomendaciones':'Continuar'}<ArrowRight size={16}/></button></div></form></div>;
}

