'use client';
import {useRouter} from 'next/navigation';
import { useState,type FormEvent } from 'react';
import Link from 'next/link';
import { ArrowRight,ShieldCheck,ArrowLeft } from 'lucide-react';
import { api,Action } from '../../components/ui';
export function AuthForm({signup,sandbox}:{signup:boolean;sandbox:boolean}){const router=useRouter();const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[message,setMessage]=useState('');
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const form=new FormData(event.currentTarget);try{const result=await api<{confirmationRequired?:boolean}>(signup?'signup':'login',{email:form.get('email'),password:form.get('password'),...(signup?{displayName:form.get('name')}: {})});if(result.confirmationRequired)setMessage('Revisa tu correo para confirmar la cuenta antes de ingresar.');else router.replace('/panel');router.refresh();}catch(e){setError(e instanceof Error?e.message:'No se pudo ingresar');}finally{setBusy(false);}}
 return <main className="auth-layout"><section className="auth-story"><Link href="/" className="brand"><span className="brand-symbol">n</span>nexo</Link><div><span className="eyebrow">TU COMPAÑÍA EMPIEZA CONTIGO</span><h1>Menos incertidumbre.<br/><em>Más camino<br/>por delante.</em></h1><p>Organiza tu próximo paso en un espacio diseñado para fundadores internacionales.</p></div><span><ShieldCheck size={16}/> Tu información, en tu propio espacio.</span></section><section className="auth-form-side"><Link className="text-link" href="/"><ArrowLeft size={15}/> Volver al inicio</Link><div className="auth-form-card"><span className="eyebrow">{signup?'HAGAMOS ESPACIO PARA TU IDEA':'BIENVENIDO DE NUEVO'}</span><h2>{signup?'Crea tu espacio':'Ingresa a tu espacio'}</h2><p>{signup?'Empieza con tu perfil. La ruta la construimos después.':'Tu siguiente paso te está esperando.'}</p>{sandbox&&<div className="notice amber">Sandbox: usa datos ficticios. No ingreses documentos personales reales.</div>}<form onSubmit={submit}>{signup&&<label>Tu nombre<input name="name" autoComplete="name" required maxLength={100}/></label>}<label>Correo electrónico<input name="email" type="email" autoComplete="email" required/></label><label>Contraseña<input name="password" aria-label="Contraseña" type="password" minLength={12} maxLength={128} autoComplete={signup?'new-password':'current-password'} required/><small>Mínimo 12 caracteres.</small></label>{error&&<p role="alert" className="error-text">{error}</p>}{message&&<p role="status" className="notice green">{message}</p>}<button className="btn full" disabled={busy}>{busy?'Un momento…':signup?'Crear cuenta':'Ingresar'}<ArrowRight size={17}/></button></form><p className="auth-alternate">{signup?'¿Ya tienes cuenta?':'¿Primera vez por aquí?'} <Link href={signup?'/ingresar':'/registro'}>{signup?'Ingresa':'Crea tu espacio'}</Link></p>{sandbox&&<div className="sandbox-ops"><span>Para explorar la operación interna</span><Action className="ghost small" onAction={async()=>{await api('sandbox-ops');router.replace('/admin');router.refresh();}}>Entrar a operaciones sandbox</Action></div>}<p className="fine-print">Al continuar aceptas el <Link href="/alcance">alcance del servicio</Link> y la <Link href="/privacidad">política preliminar de privacidad</Link>.</p></div></section></main>;
}

