import { DomainError,questionnaireSchema,assertInternal,assertCompliance,type Jurisdiction,type Questionnaire,type Role } from '../domain';
import { type Repository,type Operation,type Row } from '../persistence';
import { PRODUCTS,recommend } from '../jurisdiction-engine';
import { initializeWorkflow,advanceWorkflow,type FormationState,type StepInput } from '../workflow-engine';
import { generateObligations,remindersDue,type Obligation } from '../compliance-engine';
import { type Registry,type Rule,type Source,type SourceChange,hashText } from '../regulatory-engine';
import { registrationAdapter } from '../integrations';
import {verifiedObligations} from './obligations';
export type Actor={id:string;organizationId:string;role:Role;displayName:string};
export interface FormationRecord extends Row {id:string;organization_id:string;business_profile_id:string;jurisdiction_code:Jurisdiction;status:string;revision:number;workflow_state:FormationState;created_at:string}
export interface CompanyRecord extends Row {id:string;organization_id:string;formation_case_id:string;jurisdiction_code:Jurisdiction;legal_name:string;incorporation_date:string;registration_number:string;status:string}
export interface BusinessRecord extends Row {id:string;organization_id:string;proposed_name:string;questionnaire:Questionnaire}
const insert=(table:string,data:Row):Operation=>({kind:'insert',table,data});
const update=(table:string,data:Row,where:Row):Operation=>({kind:'update',table,data,where});
export function owned<T extends {organization_id:string}>(item:T|undefined,actor:Actor):T {if(!item || (item.organization_id!==actor.organizationId && actor.role==='customer'))throw new DomainError('NOT_FOUND','Recurso no encontrado',404);return item;}
export async function loadRegistry(repo:Repository,sandbox:boolean):Promise<Registry> {
 const [sources,authorities,rules,versions,evidence,snapshots,changes]=await Promise.all(['regulatory_sources','authorities','regulatory_rules','regulatory_rule_versions','rule_source_evidence','source_snapshots','source_change_events'].map(t=>repo.list(t)));
 const sourceModels:Source[]=sources.map(s=>({id:String(s.id),code:String(s.source_code),jurisdiction:s.jurisdiction_code as Jurisdiction,authority:String(authorities.find(a=>a.id===s.authority_id)?.name),title:String(s.title),url:String(s.canonical_url),tier:String(s.source_tier),critical:s.critical===true,refreshHours:Number(s.refresh_cadence_hours),lastCheckedAt:s.last_checked_at?new Date(String(s.last_checked_at)).toISOString():null,lastSuccessAt:s.last_success_at?new Date(String(s.last_success_at)).toISOString():null,hash:s.last_content_hash as string|null,status:s.status as Source['status']}));
 const ruleModels:Rule[]=versions.map(v=>{const r=rules.find(r=>r.id===v.rule_id)!;return {id:String(v.id),code:String(r.rule_code),version:Number(v.version),jurisdiction:r.jurisdiction_code as Jurisdiction,topic:String(r.rule_type),title:String(r.title),status:v.status as Rule['status'],severity:r.severity as Rule['severity'],effectiveFrom:String(v.effective_from).slice(0,10),effectiveTo:v.effective_to?String(v.effective_to).slice(0,10):null,verifiedAt:v.verified_at?new Date(String(v.verified_at)).toISOString():null,verifiedBy:v.verified_by as string|null,confidence:v.confidence as Rule['confidence'],outcome:v.outcome_json as Rule['outcome'],condition:v.condition_json as Rule['condition'],explanation:String(v.explanation_template),requiresHumanReview:r.requires_human_review===true,evidence:evidence.filter(e=>e.rule_version_id===v.id).map(e=>({sourceId:String(e.source_id),snapshotId:String(e.snapshot_id),snapshotHash:String(snapshots.find(s=>s.id===e.snapshot_id)?.normalized_text_hash??''),locator:String(e.source_locator),summary:String(e.evidence_summary),primary:e.is_primary===true}))};});
 return {sources:sourceModels,rules:ruleModels,changes:changes.map(c=>({id:String(c.id),sourceId:String(c.source_id),previousHash:null,newHash:'',status:c.status as SourceChange['status'],createdAt:String(c.created_at)})),sandbox};
}
export class Application {
 constructor(public repo:Repository,public sandbox:boolean){}
 async audit(actor:Actor,action:string,resource:string,resourceId:string){await this.repo.atomic([insert('audit_logs',{organization_id:actor.organizationId,actor_user_id:actor.id,action,resource_type:resource,resource_id:resourceId})]);}
 async onboard(actor:Actor,input:unknown,founder?:{firstName:string;lastName:string;dateOfBirth:string}) {
  const q=questionnaireSchema.parse(input);const id=crypto.randomUUID();const ops:Operation[]=[insert('business_profiles',{id,organization_id:actor.organizationId,created_by:actor.id,proposed_name:q.proposedName,activity_summary:q.activity,expected_annual_revenue_minor:q.expectedRevenueMinor,expected_currency:q.currency,customer_countries:q.customerCountries,operating_countries:q.operatingCountries,has_employees:q.hasEmployees,plans_fundraising:q.plansFundraising,requires_usd_account:q.requiresUsd,requires_eur_account:q.requiresEur,needs_stripe:q.needsStripe,crypto_exposure:q.crypto,regulated_activity:q.regulated,physical_inventory:q.inventory,questionnaire:q}),insert('consents',{organization_id:actor.organizationId,user_id:actor.id,consent_type:'scope_privacy',policy_version:'2026-08-31',metadata:{sandbox:this.sandbox}})];
  for(const [key,value]of Object.entries(q))ops.push(insert('questionnaire_answers',{organization_id:actor.organizationId,business_profile_id:id,question_code:key,answer_json:value,answer_version:1}));
  if(founder){const founderId=crypto.randomUUID();ops.push(insert('founder_profiles',{id:founderId,organization_id:actor.organizationId,user_id:actor.id,legal_first_name:founder.firstName,legal_last_name:founder.lastName,date_of_birth:founder.dateOfBirth,nationality_country_code:q.nationality,residence_country_code:q.residence,onboarding_status:'submitted'}));for(const country of q.taxResidences)ops.push(insert('founder_tax_residencies',{organization_id:actor.organizationId,founder_id:founderId,country_code:country,status:'declared'}));ops.push(insert('business_owners',{organization_id:actor.organizationId,business_profile_id:id,founder_id:founderId,owner_type:'natural_person',legal_name:`${founder.firstName} ${founder.lastName}`,ownership_percent:q.ownershipPercent,voting_percent:q.ownershipPercent,is_ubo:q.ownershipPercent>25}));}
  await this.repo.atomic(ops);return {businessId:id,recommendations:recommend(q,await loadRegistry(this.repo,this.sandbox))};
 }
 async createCase(actor:Actor,businessId:string,jurisdiction:Jurisdiction) {
  const business=owned((await this.repo.list<BusinessRecord>('business_profiles',{id:businessId}))[0],actor);const q=questionnaireSchema.parse(business.questionnaire);
  const registry=await loadRegistry(this.repo,this.sandbox);const recommendation=recommend(q,registry).find(r=>r.jurisdiction===jurisdiction)!;
  const product=PRODUCTS[jurisdiction];const id=crypto.randomUUID();const risk=q.regulated||q.crypto||q.founderCount>1;
  const state=initializeWorkflow(jurisdiction,product.workflow,risk);
  const ops:Operation[]=[insert('formation_cases',{id,organization_id:business.organization_id,business_profile_id:business.id,jurisdiction_code:jurisdiction,entity_type_code:product.entity,product_code:product.code,execution_mode:this.sandbox?'SANDBOX':'GUIDED',status:state.status,recommendation_score:recommendation.score,recommendation_explanation:recommendation,workflow_state:state}),...state.steps.map((s,i)=>insert('case_steps',{organization_id:business.organization_id,case_id:id,step_code:s.code,sequence:i,status:s.status,assigned_actor_type:s.actor})),insert('case_events',{organization_id:business.organization_id,case_id:id,event_type:'CASE_CREATED',actor_type:actor.role,actor_user_id:actor.id,payload:{jurisdiction,sandbox:this.sandbox}})];
  if(risk)ops.push(insert('case_escalations',{organization_id:business.organization_id,case_id:id,escalation_type:'onboarding_risk',severity:'HIGH',reason:'Revisar actividad, riesgo y estructura de titularidad antes de avanzar'}));
  await this.repo.atomic(ops);return{id};
 }
 async approveRisk(actor:Actor,caseId:string,reason:string){assertCompliance(actor.role);if(reason.trim().length<20)throw new DomainError('REASON_REQUIRED','Documenta la revisión (mínimo 20 caracteres)');if(!this.sandbox)throw new DomainError('EXTERNAL_BLOCKED','Se requiere proveedor de screening configurado y evidencia de revisión',409);const c=owned((await this.repo.list<FormationRecord>('formation_cases',{id:caseId}))[0],actor);const state=structuredClone(c.workflow_state);state.signals.riskApproved=true;state.status='AWAITING_PAYMENT';state.revision++;await this.repo.atomic([update('formation_cases',{workflow_state:state,status:state.status,revision:state.revision},{id:caseId,revision:c.revision}),insert('risk_assessments',{organization_id:c.organization_id,case_id:caseId,subject_type:'case',subject_id:caseId,risk_level:'HIGH',decision:'sandbox_approved',reasons:[reason],decided_by:actor.id,model_or_rules_version:'manual-1'})]);}
 async advance(actor:Actor,caseId:string,input:StepInput) {
  const c=owned((await this.repo.list<FormationRecord>('formation_cases',{id:caseId}))[0],actor);const business=owned((await this.repo.list<BusinessRecord>('business_profiles',{id:c.business_profile_id}))[0],{...actor,organizationId:c.organization_id});
  const next=advanceWorkflow(c.workflow_state,input,actor,{sandbox:this.sandbox,questionnaire:business.questionnaire});
  const step=next.steps.find(s=>s.code===input.stepCode)!;
  const org=c.organization_id;const ops:Operation[]=[update('formation_cases',{status:next.status,workflow_state:next,revision:next.revision,...(next.registered&&!c.workflow_state.registered?{registered_at:new Date().toISOString()}:{}),...(step.gate==='filing'?{submitted_at:new Date().toISOString()}: {})},{id:c.id,revision:c.revision}),update('case_steps',{status:'completed',completed_at:step.completedAt,external_reference:step.reference??null},{case_id:c.id,step_code:step.code}),insert('case_events',{organization_id:org,case_id:c.id,event_type:input.mock?'SANDBOX_STEP_COMPLETED':'STEP_COMPLETED',actor_type:actor.role,actor_user_id:actor.id,payload:{step:step.code,reference:step.reference??null}})];
  let companyId:string|undefined;
  if(next.registered&&!c.workflow_state.registered){
   const result=await registrationAdapter(c.jurisdiction_code,this.sandbox).submit({caseId:c.id,jurisdiction:c.jurisdiction_code,name:business.proposed_name});
   companyId=crypto.randomUUID();const date=new Date().toISOString().slice(0,10);const end=`${date.slice(0,4)}-12-31`;
   ops.push(insert('companies',{id:companyId,organization_id:org,formation_case_id:c.id,jurisdiction_code:c.jurisdiction_code,entity_type_code:PRODUCTS[c.jurisdiction_code].entity,legal_name:business.proposed_name,registration_number:result.reference,incorporation_date:date,status:'SANDBOX'}));
   const registry=await loadRegistry(this.repo,this.sandbox);const obligations=generateObligations({id:companyId,jurisdiction:c.jurisdiction_code,incorporationDate:date,financialYearEnd:end,wyomingAssetsMinor:business.questionnaire.wyomingAssetsMinor,foreignOwnedDisregarded:business.questionnaire.foreignOwnedDisregarded},registry);
   for(const o of obligations)ops.push(insert('company_obligations',{organization_id:org,company_id:companyId,obligation_code:o.code,title:o.title,period_start:o.periodStart,period_end:o.periodEnd,due_at:o.dueDate?`${o.dueDate}T12:00:00Z`:null,status:o.status,amount_minor:o.amountMinor,currency:o.currency,source_rule_version_id:o.ruleVersionId,notes:o.notes,evidence_json:o.evidence}));
   ops.push(insert('notifications',{organization_id:org,title:'Compañía simulada creada',message:'Tu calendario de obligaciones está disponible. Este registro no tiene efecto legal.',deduplication_key:`registered:${c.id}`,channel:'in_app',status:'sent',sent_at:new Date().toISOString()}));
  }
  await this.repo.atomic(ops);return{caseId:c.id,companyId,status:next.status};
 }
 async prepareOrder(actor:Actor,caseId:string) {
  const c=owned((await this.repo.list<FormationRecord>('formation_cases',{id:caseId}))[0],actor);
  if(c.workflow_state.paid)throw new DomainError('ALREADY_PAID','El caso ya está pagado',409);
  const prior=(await this.repo.list('orders',{formation_case_id:caseId})).find(o=>o.status==='pending');if(prior)return prior;
  const products=await this.repo.list('billing_products',{code:'PLATFORM_SETUP'});const prices=await this.repo.list('billing_prices',{billing_product_id:products[0].id,active:true});
  const now=Date.now();const price=prices.find(p=>(!p.valid_from||Date.parse(String(p.valid_from))<=now)&&(!p.valid_to||Date.parse(String(p.valid_to))>now));if(!price)throw new DomainError('PRICE_UNAVAILABLE','Precio de plataforma pendiente',409);
  const id=crypto.randomUUID();const amount=Number(price.amount_minor);
  const order={id,organization_id:c.organization_id,formation_case_id:caseId,status:'pending',currency:price.currency,subtotal_minor:amount,platform_fee_minor:amount,government_fee_minor:null,partner_fee_minor:null,total_minor:amount,idempotency_key:`setup:${caseId}`};
  await this.repo.atomic([insert('orders',order)]);return order;
 }
 async settleOrder(orderId:string,options:{mock:boolean;sessionId?:string;amount?:number;currency?:string;eventId?:string;eventHash?:string},actor?:Actor) {
  if(options.mock && !this.sandbox)throw new DomainError('MOCK_DENIED','Pago simulado deshabilitado',403);
  const order=(await this.repo.list('orders',{id:orderId}))[0];if(!order)throw new DomainError('NOT_FOUND','Orden no encontrada',404);if(actor)owned(order as Row&{organization_id:string},actor);
  if(options.eventId && (await this.repo.list('webhook_events',{id:options.eventId})).length)return{duplicate:true};
  if(order.status==='paid'||order.status==='sandbox_paid')return{duplicate:true};
  if(!options.mock && (order.stripe_checkout_session_id!==options.sessionId||Number(order.total_minor)!==options.amount||String(order.currency).toLowerCase()!==options.currency?.toLowerCase()))throw new DomainError('PAYMENT_MISMATCH','La sesión de pago no coincide con la orden',409);
  const c=(await this.repo.list<FormationRecord>('formation_cases',{id:order.formation_case_id}))[0];const state=structuredClone(c.workflow_state);state.paid=true;state.status=state.signals.riskApproved?'ONBOARDING':'REVIEW_REQUIRED';state.revision++;
  const ops:Operation[]=[update('orders',{status:options.mock?'sandbox_paid':'paid',paid_at:new Date().toISOString()},{id:orderId,status:'pending'}),update('formation_cases',{workflow_state:state,status:state.status,revision:state.revision},{id:c.id,revision:c.revision}),insert('case_events',{organization_id:c.organization_id,case_id:c.id,event_type:options.mock?'SANDBOX_PAYMENT':'PAYMENT_CONFIRMED',actor_type:options.mock?'customer':'stripe',actor_user_id:actor?.id??null,payload:{orderId}})];
  if(options.eventId)ops.push(insert('webhook_events',{id:options.eventId,provider:'stripe',payload_hash:options.eventHash??hashText(options.eventId)}));
  await this.repo.atomic(ops);return{paid:true};
 }
 async notifications(actor:Actor,today=new Date().toISOString().slice(0,10)) {
  const obligations=verifiedObligations(await this.repo.list('company_obligations',actor.role==='customer'?{organization_id:actor.organizationId}:{}),await loadRegistry(this.repo,this.sandbox));
  const mapped=obligations.map(o=>({id:String(o.id),code:String(o.obligation_code),title:String(o.title),periodStart:String(o.period_start),periodEnd:String(o.period_end),dueDate:o.due_at?new Date(String(o.due_at)).toISOString().slice(0,10):null,amountMinor:o.amount_minor?Number(o.amount_minor):null,currency:String(o.currency),status:o.status as Obligation['status'],ruleVersionId:o.source_rule_version_id as string|null,evidence:o.evidence_json as Obligation['evidence'],notes:String(o.notes)}));
  const reminders=remindersDue(mapped,today);const existing=await this.repo.list('notifications');const ops=reminders.filter(r=>!existing.some(n=>n.deduplication_key===r.key)).map(r=>insert('notifications',{organization_id:obligations.find(o=>o.id===r.obligationId)!.organization_id,company_obligation_id:r.obligationId,title:r.title,message:r.message,deduplication_key:r.key,channel:'in_app',status:'sent',sent_at:new Date().toISOString()}));if(ops.length)await this.repo.atomic(ops);return{created:ops.length};
 }
 async support(actor:Actor,subject:string,message:string){const id=crypto.randomUUID();await this.repo.atomic([insert('support_tickets',{id,organization_id:actor.organizationId,user_id:actor.id,subject,message})]);return{id};}
 async documentReview(actor:Actor,id:string,approve:boolean){assertInternal(actor.role);const doc=(await this.repo.list('case_documents',{id}))[0];if(!doc)throw new DomainError('NOT_FOUND','Documento no encontrado',404);await this.repo.atomic([update('case_documents',{status:approve?'approved':'rejected'},{id}),insert('audit_logs',{organization_id:doc.organization_id,actor_user_id:actor.id,action:approve?'DOCUMENT_APPROVED':'DOCUMENT_REJECTED',resource_type:'case_documents',resource_id:id})]);}
}
