import type { PublicLocale } from '../lib/public-locale';

const en = {
  nav: ['How it works', 'Jurisdictions', 'Compliance', 'Pricing'],
  signIn: 'Sign in', start: 'Get started', navigation: 'Main navigation', openMenu: 'Open navigation', closeMenu: 'Close navigation', language: 'Language',
  sandbox: 'SANDBOX ENVIRONMENT', sandboxNote: 'Explore with test data. No real filings or charges are made.',
  eyebrow: 'FOR FOUNDERS WITHOUT BORDERS', hero: ['Your next chapter.', 'Your company,', 'in order.'],
  intro: 'From your first question to your next deadline. Compare options, coordinate your company formation and stay in control of what comes next.',
  build: 'Build my path', explore: 'Explore jurisdictions', heroNote: 'Clear steps. Official sources. People when you need them.',
  map: 'YOUR FORMATION ROADMAP', routes: '4 available paths', mapTitle: ['A good start begins', 'with a clear plan.'], next: 'NEXT',
  steps: [
    ['01', 'We understand your business', 'Your activity, your plans and your context'],
    ['02', 'We map your path', 'Requirements and costs, in plain sight'],
    ['03', 'We move forward together', 'A clear owner for every step'],
    ['04', 'We keep track of what follows', 'Obligations that stay on your radar'],
  ],
  countriesLine: 'Delaware · Wyoming · Estonia · United Kingdom', responsibilities: 'ONE PLATFORM. CLEAR RESPONSIBILITIES.',
  actors: ['You complete', 'We prepare', 'The partner reviews', 'The government decides'],
  choose: 'CHOOSE WITH CONTEXT', compareTitle: 'Four paths. Your own criteria.',
  compareIntro: ['The right option depends on your business.', 'We start with your needs, not tax promises.'],
  countries: [
    { name: 'Delaware', tag: 'An established corporate framework' },
    { name: 'Wyoming', tag: 'A path for your business in the US' },
    { name: 'Estonia', tag: 'A company you can manage digitally' },
    { name: 'United Kingdom', tag: 'Your business in the British market' },
  ],
  explorePath: 'Explore this path',
  compareNote: 'Your personalized assessment shows requirements, verified fees, mandatory services and items awaiting review. We do not guarantee incorporation, bank accounts or tax treatment.',
  formationPath: 'COMPANY FORMATION PATH', countryIntro: 'Start with your profile to see the requirements that apply to your activity and structure.',
  countryFeatures: [
    ['One case, every step', 'From initial information to registration confirmation, each step shows whether it depends on you, us, a partner or the government.'],
    ['Requirements backed by evidence', 'Fees and obligations come from versioned rules. If current verification is missing, we let you know before you proceed.'],
  ],
  evaluate: 'Assess my business', howEyebrow: 'FROM CONTEXT TO ACTION', howTitle: ['Know what comes next.', 'And who takes care of it.'],
  howSteps: [
    ['01', 'Tell us about your business', 'Nationality, residence, activity, owners and plans. We save your answers in a private workspace.'],
    ['02', 'Compare the four paths', 'Review the advantages, warnings, requirements and sources for each jurisdiction.'],
    ['03', 'Prepare your case', 'Organize documents, reviews and actions with the relevant providers.'],
    ['04', 'Track your obligations', 'Check your calendar, sources and notices of regulatory changes.'],
  ],
  startAssessment: 'Start my assessment', complianceEyebrow: 'AFTER REGISTRATION, WE ARE STILL HERE',
  complianceTitle: ['Your next deadline', 'should not be a surprise.'],
  complianceIntro: 'A calendar with obligations, context and sources. Official changes are sent for review before they become instructions for your business.',
  findPath: 'Find my path',
  principles: [
    ['Dates with a foundation', 'Each obligation retains the version of the rule that created it.'],
    ['Verified, or under review', 'If a source expires or changes, the answer is blocked until verification.'],
    ['An international perspective', 'Incorporation does not remove obligations where you live and operate.'],
  ],
  pricingEyebrow: 'EVERY COST IN ITS PLACE', pricingTitle: ['Clarity from', 'the very first invoice.'],
  pricing: [
    ['01', 'Platform fee', 'Preparation and coordination. You will see the confirmed price in your order before checkout.'],
    ['02', 'Government fees', 'Shown separately when a current rule is available. They are not collected as part of the MVP platform fee.'],
    ['03', 'Partner services', 'Agent, address, contact person or professional review: subject to a quote and a contract.'],
    ['04', 'Ongoing compliance', 'A separate subscription. Requires Stripe Billing configuration before activation.'],
  ],
  legalEyebrow: 'TRANSPARENCY · MVP DRAFT', legalTitles: { terminos: 'Terms of use', privacidad: 'Privacy', alcance: 'Scope of service' },
  legalIntro: 'Preliminary document for the test environment. The operator’s identity, contracts and final policies require review before the service is offered to the public.',
  privacy: [
    ['Data we need', 'The product organizes founder, activity, ownership and document information. Use fictitious information only in sandbox. Documents remain private and are subject to review.'],
    ['Access and third parties', 'Users can only access their own organization. Authorized internal staff can review cases. No data will be sent to providers without configuring and documenting that integration.'],
    ['Retention and rights', 'Retention periods, responsible parties, international transfers and the process for exercising rights must be defined contractually before commercial operation. You can submit a request through Support.'],
  ],
  scope: [
    ['What we do', 'We orchestrate information, preparation, documentation, coordination and follow-up. Official sources support the rules; professional and government decisions remain with the responsible parties.'],
    ['What we do not guarantee', 'We do not guarantee incorporation, banking, Stripe, KYC approval, tax residency or tax outcomes. Offering this platform does not make us a legal advisor, authority, bank, notary, KYC provider or ACSP.'],
    ['Costs and authorizations', 'Platform charges, government fees, mandatory services and optional services are distinguished. No simulated payment represents an actual charge or a submitted filing.'],
  ],
  footer: 'A space for your next chapter.', footerNav: ['Scope', 'Privacy', 'Terms'], localeLabel: 'EN · GLOBAL',
};

const es: typeof en = {
  nav: ['Cómo funciona', 'Jurisdicciones', 'Cumplimiento', 'Precios'],
  signIn: 'Ingresar', start: 'Empezar', navigation: 'Navegación principal', openMenu: 'Abrir navegación', closeMenu: 'Cerrar navegación', language: 'Idioma',
  sandbox: 'ENTORNO SANDBOX', sandboxNote: 'Explora con datos de prueba. No se realizan trámites ni cobros reales.',
  eyebrow: 'PARA FUNDADORES SIN FRONTERAS', hero: ['Tu próximo capítulo.', 'Tu compañía,', 'en orden.'],
  intro: 'De la primera pregunta al próximo vencimiento. Compara opciones, coordina tu constitución y mantén el control de lo que sigue.',
  build: 'Construir mi ruta', explore: 'Explorar jurisdicciones', heroNote: 'Pasos claros. Fuentes oficiales. Personas cuando hacen falta.',
  map: 'TU MAPA DE CONSTITUCIÓN', routes: '4 rutas disponibles', mapTitle: ['Un buen comienzo', 'tiene un plan claro.'], next: 'SIGUIENTE',
  steps: [
    ['01', 'Entendemos tu negocio', 'Tu actividad, tus planes y tu contexto'],
    ['02', 'Encontramos tu ruta', 'Requisitos y costos, a la vista'],
    ['03', 'Avanzamos contigo', 'Cada paso con su responsable'],
    ['04', 'Cuidamos lo que sigue', 'Obligaciones que no quedan en el olvido'],
  ],
  countriesLine: 'Delaware · Wyoming · Estonia · Reino Unido', responsibilities: 'UNA PLATAFORMA. RESPONSABILIDADES CLARAS.',
  actors: ['Tú completas', 'Nosotros preparamos', 'El partner revisa', 'El gobierno decide'],
  choose: 'ELIGE CON CONTEXTO', compareTitle: 'Cuatro rutas. Tu propio criterio.',
  compareIntro: ['La mejor opción depende de tu negocio.', 'Empezamos por tus necesidades, no por promesas fiscales.'],
  countries: [
    { name: 'Delaware', tag: 'Un marco corporativo reconocido' },
    { name: 'Wyoming', tag: 'Una ruta para tu negocio en EE. UU.' },
    { name: 'Estonia', tag: 'Una compañía con gestión digital' },
    { name: 'Reino Unido', tag: 'Tu negocio en el mercado británico' },
  ],
  explorePath: 'Explorar la ruta',
  compareNote: 'La evaluación personalizada muestra requisitos, tasas verificadas, servicios obligatorios y pendientes de revisión. No garantizamos constitución, cuentas bancarias ni tratamiento fiscal.',
  formationPath: 'RUTA DE CONSTITUCIÓN', countryIntro: 'Comienza con tu perfil para ver los requisitos que aplican a tu actividad y estructura.',
  countryFeatures: [
    ['Un expediente, todos los pasos', 'Desde la información inicial hasta la confirmación del registro, cada paso indica si depende de ti, de nosotros, de un partner o del gobierno.'],
    ['Requisitos con evidencia', 'Las tasas y obligaciones se consultan desde reglas versionadas. Si falta una verificación vigente, te lo indicamos antes de avanzar.'],
  ],
  evaluate: 'Evaluar mi negocio', howEyebrow: 'DEL CONTEXTO A LA ACCIÓN', howTitle: ['Sabes qué sigue.', 'Y quién lo hace.'],
  howSteps: [
    ['01', 'Cuéntanos sobre tu negocio', 'Nacionalidad, residencia, actividad, propietarios y planes. Guardamos tus respuestas en un espacio privado.'],
    ['02', 'Compara las cuatro rutas', 'Revisa las ventajas, advertencias, requisitos y fuentes de cada jurisdicción.'],
    ['03', 'Prepara tu expediente', 'Organiza documentos, revisiones y acciones con los proveedores que correspondan.'],
    ['04', 'Sigue tus obligaciones', 'Consulta tu calendario, las fuentes y los avisos de cambios regulatorios.'],
  ],
  startAssessment: 'Empezar mi evaluación', complianceEyebrow: 'DESPUÉS DEL REGISTRO, SEGUIMOS AQUÍ',
  complianceTitle: ['Que el siguiente vencimiento', 'no sea una sorpresa.'],
  complianceIntro: 'Un calendario con obligaciones, contexto y fuentes. Los cambios oficiales se envían a revisión antes de convertirse en instrucciones para tu negocio.',
  findPath: 'Conocer mi ruta',
  principles: [
    ['Fechas con fundamento', 'Cada obligación conserva la versión de la regla que la originó.'],
    ['Verificado, o en revisión', 'Si la fuente vence o cambia, la respuesta se bloquea hasta verificar.'],
    ['Perspectiva internacional', 'La constitución no elimina las obligaciones donde vives y operas.'],
  ],
  pricingEyebrow: 'CADA COSTO EN SU LUGAR', pricingTitle: ['Claridad desde', 'la primera factura.'],
  pricing: [
    ['01', 'Tarifa de plataforma', 'Preparación y coordinación. Verás el precio confirmado en tu orden antes del checkout.'],
    ['02', 'Tasas de gobierno', 'Se muestran por separado cuando existe una regla vigente. No se cobran dentro de la tarifa de plataforma del MVP.'],
    ['03', 'Servicios de partners', 'Agente, domicilio, contacto o revisión profesional: sujetos a una cotización y un contrato.'],
    ['04', 'Cumplimiento continuo', 'Suscripción separada. Requiere configuración de Stripe Billing antes de activarse.'],
  ],
  legalEyebrow: 'TRANSPARENCIA · BORRADOR MVP', legalTitles: { terminos: 'Términos de uso', privacidad: 'Privacidad', alcance: 'Alcance del servicio' },
  legalIntro: 'Documento preliminar para el entorno de prueba. La identidad del operador, los contratos y las políticas definitivas requieren revisión antes de ofrecer el servicio al público.',
  privacy: [
    ['Datos que necesitamos', 'El producto organiza información de fundadores, actividades, titularidad y documentos. En sandbox utiliza únicamente información ficticia. Los documentos permanecen privados y pasan por revisión.'],
    ['Acceso y terceros', 'Los usuarios solo acceden a su organización. El equipo interno autorizado puede revisar expedientes. No se enviarán datos a proveedores sin configurar y documentar esa integración.'],
    ['Retención y derechos', 'El plazo de retención, responsables, transferencias internacionales y mecanismo de ejercicio de derechos deben definirse contractualmente antes de la operación comercial. Puedes registrar una solicitud desde Soporte.'],
  ],
  scope: [
    ['Qué hacemos', 'Orquestamos información, preparación, documentación, coordinación y seguimiento. Las fuentes oficiales sustentan las reglas; las decisiones profesionales y gubernamentales permanecen con sus responsables.'],
    ['Qué no garantizamos', 'No garantizamos constitución, banca, Stripe, aprobación KYC, residencia fiscal ni resultados tributarios. No somos un asesor legal, una autoridad, un banco, un notario, un proveedor KYC ni un ACSP por el solo hecho de ofrecer la plataforma.'],
    ['Costos y autorizaciones', 'La plataforma, el gobierno, los servicios obligatorios y los opcionales se distinguen. Ningún pago simulado representa un cobro real ni un trámite presentado.'],
  ],
  footer: 'Un espacio para tu siguiente capítulo.', footerNav: ['Alcance', 'Privacidad', 'Términos'], localeLabel: 'ES · LATAM',
};

export const publicCopy: Record<PublicLocale, typeof en> = { en, es };
