'use client';
import {useState} from 'react';
import type {Rule,Source} from '../../../packages/regulatory-engine';
import type {Row} from '../../../packages/persistence';
import {Action,api} from './ui';
export function RuleEditor({rule,sources,snapshots,reload}:{rule:Rule;sources:Source[];snapshots:Row[];reload:()=>Promise<void>}){
 const[outcome,setOutcome]=useState(JSON.stringify(rule.outcome,null,2));const[explanation,setExplanation]=useState(rule.explanation);const[effectiveFrom,setEffectiveFrom]=useState(new Date().toISOString().slice(0,10));const[snapshotId,setSnapshotId]=useState('');const[locator,setLocator]=useState('');const[summary,setSummary]=useState('');
 const available=snapshots.filter(s=>s.fetch_status==='success').sort((a,b)=>String(b.fetched_at).localeCompare(String(a.fetched_at)));
 return <details className="rule-editor"><summary>Preparar nueva versión y evidencia</summary><p>Editar crea un borrador independiente. Publicar exige una revisión humana posterior y fuentes vigentes.</p><label>Fecha efectiva<input type="date" value={effectiveFrom} onChange={e=>setEffectiveFrom(e.target.value)}/></label><label>Resultado estructurado (JSON)<textarea rows={7} value={outcome} onChange={e=>setOutcome(e.target.value)}/></label><label>Explicación para el cliente<textarea rows={4} value={explanation} onChange={e=>setExplanation(e.target.value)}/></label><label>Snapshot de evidencia<select value={snapshotId} onChange={e=>setSnapshotId(e.target.value)}><option value="">Seleccionar captura</option>{available.map(s=><option value={String(s.id)} key={String(s.id)}>{sources.find(source=>source.id===s.source_id)?.code} · {String(s.fetched_at).slice(0,16)}{s.storage_path?'':' · fixture'}</option>)}</select></label>{snapshotId&&<a className="text-link" href={`/api/source-snapshot?id=${snapshotId}`}>Descargar evidencia para revisar</a>}<label>Sección o localizador<input value={locator} onChange={e=>setLocator(e.target.value)} placeholder="Artículo, sección o párrafo verificable"/></label><label>Resumen de evidencia<textarea value={summary} rows={3} onChange={e=>setSummary(e.target.value)} placeholder="Explica cómo la fuente respalda cada valor del resultado."/></label><Action className="small secondary" onAction={async()=>{let parsed:unknown;try{parsed=JSON.parse(outcome);}catch{throw new Error('Revisa la sintaxis del resultado JSON');}await api('rule-draft',{versionId:rule.id,effectiveFrom,outcome:parsed,explanation,evidence:[{snapshotId,locator,summary}]});await reload();}}>Guardar borrador para revisión</Action></details>;
}
