'use client';
import { useState,type ReactNode } from 'react';
import { LoaderCircle,ArrowUpRight,ShieldCheck } from 'lucide-react';
import type { Fact } from '../../../packages/regulatory-engine';
export async function api<T=Record<string,unknown>>(action:string,body:unknown={}):Promise<T>{const response=await fetch(`/api/${action}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error||'No se pudo completar la operación');return result as T;}
export function Action({children,onAction,className='',disabled=false}:{children:ReactNode;onAction:()=>Promise<unknown>;className?:string;disabled?:boolean}){const[busy,setBusy]=useState(false);const[error,setError]=useState('');return <><button type="button" className={`btn ${className}`} disabled={busy||disabled} onClick={async()=>{setBusy(true);setError('');try{await onAction();}catch(e){setError(e instanceof Error?e.message:'Ocurrió un error');}finally{setBusy(false);}}}>{busy?<LoaderCircle size={16} className="spin"/>:null}{children}</button>{error&&<p className="error-text" role="alert">{error}</p>}</>;}
export function Badge({children,tone='neutral'}:{children:ReactNode;tone?:'neutral'|'green'|'amber'|'blue'}){return <span className={`badge ${tone}`}>{children}</span>;}
export function Empty({title,description,action}:{title:string;description:string;action?:ReactNode}){return <div className="empty-state"><span className="empty-mark"><ShieldCheck size={26}/></span><h3>{title}</h3><p>{description}</p>{action}</div>;}
export function Evidence({facts}:{facts:Fact[]}){return <div className="evidence-list">{facts.map((f,i)=><details key={`${f.rule_version_id}-${i}`}><summary><ShieldCheck size={14}/><span>{f.authority}</span><small>Ver evidencia</small></summary><p><a href={f.canonical_url} target="_blank" rel="noreferrer">{f.source_title} <ArrowUpRight size={13}/></a></p><dl><dt>Última consulta</dt><dd>{formatDate(f.last_checked_at)}</dd><dt>Verificación</dt><dd>{formatDate(f.last_verified_at)}</dd><dt>Vigente desde</dt><dd>{formatDate(f.effective_from)}</dd><dt>Confianza</dt><dd>{f.confidence}</dd><dt>Versión</dt><dd>{f.rule_code} · {f.rule_version_id}</dd></dl></details>)}</div>;}
export function formatDate(value:unknown){if(!value)return 'Pendiente';const date=new Date(String(value));return Number.isNaN(date.getTime())?'Pendiente':new Intl.DateTimeFormat('es-419',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}).format(date);}
export function money(amount:unknown,currency='USD'){return amount===null||amount===undefined?'Por confirmar':new Intl.NumberFormat('es-419',{style:'currency',currency}).format(Number(amount)/100);}
export const statusLabels:Record<string,string>={AWAITING_PAYMENT:'Pendiente de pago',ONBOARDING:'En preparación',REVIEW_REQUIRED:'Revisión requerida',REGISTERED:'Constituida',POST_FORMATION:'Postconstitución',ACTIVE_COMPLIANCE:'Cumplimiento activo',SUBMITTED:'Presentada',pending:'Pendiente',completed:'Completado',review_required:'Revisión requerida',quarantined:'En revisión',approved:'Aprobado',rejected:'Rechazado',paid:'Pagado',sandbox_paid:'Pago simulado',SANDBOX:'Registro simulado',ACTIVE:'Activa',PENDING_REVIEW:'Pendiente de revisión',NEEDS_REVIEW:'Reverificación',verified:'Verificada',unverified:'Sin verificar',needs_review:'Revisión pendiente',error:'Consulta fallida',open:'Abierto',resolved:'Resuelto'};
