import {readFileSync,writeFileSync} from 'node:fs';
const sources=JSON.parse(readFileSync('regulatory/source-manifests/official_sources.json','utf8'));
const rules=JSON.parse(readFileSync('regulatory/normalized/rule-candidates.json','utf8'));
const quote=s=>`'${String(s).replaceAll("'","''")}'`;
let sql=`-- Production seed contains no active legal rules or synthetic approvals.\nbegin;\ninsert into jurisdictions(code,country_code,subdivision_code,name,default_currency,timezone) values\n('US-DE','US','DE','Delaware','USD','America/New_York'),('US-WY','US','WY','Wyoming','USD','America/Denver'),('EE','EE',null,'Estonia','EUR','Europe/Tallinn'),('GB','GB',null,'Reino Unido','GBP','Europe/London') on conflict do nothing;\n`;
sql+=`insert into entity_types(code,jurisdiction_code,legal_name,short_name) values ('US_DE_LLC','US-DE','Limited Liability Company','LLC'),('US_WY_LLC','US-WY','Limited Liability Company','LLC'),('EE_OU','EE','Osaühing','OÜ'),('GB_LTD','GB','Private company limited by shares','Ltd') on conflict do nothing;\n`;
for(const s of sources){sql+=`insert into authorities(name,jurisdiction_code,authority_type,official_domain) values(${quote(s.authority)},${quote(s.jurisdiction)},'government',${quote(new URL(s.url).hostname)}) on conflict(name) do nothing;\n`;sql+=`insert into regulatory_sources(source_code,authority_id,jurisdiction_code,title,canonical_url,source_tier,source_category,refresh_cadence_hours,critical) values(${quote(s.source_code)},(select id from authorities where name=${quote(s.authority)}),${quote(s.jurisdiction)},${quote(s.title)},${quote(s.url)},${quote(s.tier)},${quote(s.category)},${s.refresh_hours},${s.critical}) on conflict(source_code) do nothing;\n`;}
for(const r of rules){sql+=`insert into regulatory_rules(rule_code,jurisdiction_code,rule_type,title,description,severity,automation_level,requires_human_review) values(${quote(r.code)},${quote(r.jurisdiction)},${quote(r.topic)},${quote(r.title)},${quote(r.explanation)},'CRITICAL','B_AUTOMATABLE_WITH_REVIEW',${r.review}) on conflict(rule_code) do nothing;\n`;sql+=`insert into regulatory_rule_versions(rule_id,version,status,effective_from,outcome_json,explanation_template) values((select id from regulatory_rules where rule_code=${quote(r.code)}),1,'PENDING_REVIEW',${quote(r.effectiveFrom||'2026-08-31')},${quote(JSON.stringify(r.outcome))}::jsonb,${quote(r.explanation)}) on conflict(rule_id,version) do nothing;\n`;}
sql+=`insert into billing_products(code,name,type,metadata) values ('PLATFORM_SETUP','Preparación y coordinación','formation','{"excludes_government_fees":true,"excludes_partner_fees":true}'),('COMPLIANCE_ANNUAL','Seguimiento de cumplimiento','compliance','{}') on conflict(code) do nothing;\n`;
sql+=`insert into billing_prices(billing_product_id,currency,amount_minor,interval,valid_from) select id,'USD',9900,'one_time','2026-08-31' from billing_products where code='PLATFORM_SETUP';\ncommit;\n`;
writeFileSync('supabase/seed.sql',sql);
