import { NextRequest,NextResponse } from 'next/server';
import { z } from 'zod';
import { DomainError,JURISDICTIONS,assertInternal,assertCompliance,founderSchema } from '../../../../../packages/domain';
import { loadRegistry,type BusinessRecord,type FormationRecord,owned } from '../../../../../packages/application';
import { recommend } from '../../../../../packages/jurisdiction-engine';
import { answerRegulatoryQuestion } from '../../../../../packages/ai';
import {answerWithOpenAI} from '../../../../../packages/ai/openai';
import {verifiedObligations} from '../../../../../packages/application/obligations';
import {activateSandboxSubscription,prepareSubscription,applySubscriptionEvent} from '../../../../../packages/billing/subscriptions';
import { prepareFormationDocument } from '../../../../../packages/document-engine';
import { SandboxCheckout,StripeTestCheckout,verifyStripeEvent } from '../../../../../packages/billing';
import { hashText,ruleBlockers } from '../../../../../packages/regulatory-engine';
import { monitorSource,reviewSource,publishCandidate,createRuleDraft } from '../../../../../packages/regulatory-engine/service';
import {snapshotStorage} from '../../../lib/snapshots';
import {regenerateCompliance} from '../../../../../packages/application/compliance';
import { application,isSandbox,serverRepository,appOrigin } from '../../../lib/runtime';
import { signup,login,logout,requireActor,userRepository,sandboxOps,supabaseAuth } from '../../../lib/auth';
import { uploadDocument,signedDocument,downloadDocument } from '../../../lib/documents';
import { evaluateCaseGuide } from '../../../../../packages/formation-guidance/service';
import { googleSignIn } from '../../../lib/google-auth';
import { trackCase } from '../../../../../packages/case-tracking';
import { prepareCaseBrief } from '../../../../../packages/case-tracking/service';
export const runtime='nodejs';export const dynamic='force-dynamic';
const uuid=z.uuid();
function errorResponse(error:unknown){if(error instanceof SyntaxError)return NextResponse.json({error:'JSON inválido',code:'INVALID_JSON'},{status:400});if(error instanceof z.ZodError)return NextResponse.json({error:'Revisa los campos del formulario',code:'VALIDATION',details:error.issues.map(i=>({path:i.path,message:i.message}))},{status:400});if(error instanceof DomainError)return NextResponse.json({error:error.message,code:error.code},{status:error.status});console.error('Request failed',error instanceof Error?error.message:'unknown');return NextResponse.json({error:'No se pudo completar la operación. Intenta nuevamente.',code:'INTERNAL_ERROR'},{status:500});}
function sameOrigin(request:NextRequest){const origin=request.headers.get('origin');const allowed=[appOrigin(),...(isSandbox()?['http://127.0.0.1:3000','http://localhost:3000']:[])];if(!origin||!allowed.includes(origin))throw new DomainError('ORIGIN_DENIED','Origen de solicitud no autorizado',403);}
async function limitedBytes(request:NextRequest,max=65536){if(Number(request.headers.get('content-length'))>max)throw new DomainError('BODY_TOO_LARGE','Solicitud demasiado grande',413);const reader=request.body?.getReader();if(!reader)return new Uint8Array();const chunks:Uint8Array[]=[];let size=0;for(;;){const{done,value}=await reader.read();if(done)break;size+=value.length;if(size>max){await reader.cancel();throw new DomainError('BODY_TOO_LARGE','Solicitud demasiado grande',413);}chunks.push(value);}return new Uint8Array(Buffer.concat(chunks));}
export async function GET(request:NextRequest,context:{params:Promise<{action:string[]}>}){try{const action=(await context.params).action.join('/');const actor=await requireActor();const repo=await userRepository(actor);
 if(action==='case-tracking'){const id=request.nextUrl.searchParams.get('caseId');const cases=id?[owned((await repo.list<FormationRecord>('formation_cases',{id:uuid.parse(id)}))[0],actor)]:await repo.list<FormationRecord>('formation_cases',{}, {orderBy:'updated_at',descending:true,limit:100});const summaries=await Promise.all(cases.map(async item=>trackCase(item,await repo.list('case_events',{case_id:item.id},{orderBy:'id',descending:true,limit:100}))));return NextResponse.json({cases:summaries,checkedAt:new Date().toISOString(),limit:100},{headers:{'Cache-Control':'no-store'}});}
 if(action==='workspace'){const app=await application();const tables=['business_profiles','formation_cases','case_steps','case_events','case_tasks','case_documents','companies','company_obligations','orders','subscriptions','notifications','support_tickets','case_escalations','regulatory_alerts'];const lists=await Promise.all(tables.map(t=>repo.list(t)));const registry=await loadRegistry(app.repo,isSandbox());lists[tables.indexOf('company_obligations')]=verifiedObligations(lists[tables.indexOf('company_obligations')],registry);if(actor.role==='customer'){registry.rules=registry.rules.filter(r=>ruleBlockers(r,registry).length===0);registry.changes=[];}const admin:Record<string,unknown>={};if(actor.role!=='customer')for(const t of ['partners','source_change_events','audit_logs','profiles','source_snapshots'])admin[t]=await repo.list(t);return NextResponse.json({actor,sandbox:isSandbox(),records:Object.fromEntries(tables.map((t,i)=>[t,lists[i]])),registry,admin},{headers:{'Cache-Control':'no-store'}});}
 if(action==='source-snapshot'){assertCompliance(actor.role);const id=uuid.parse(request.nextUrl.searchParams.get('id'));const row=(await repo.list('source_snapshots',{id}))[0];if(!row?.storage_path)throw new DomainError('SNAPSHOT_UNAVAILABLE','Snapshot de fixture o contenido no disponible',404);return new Response(await(await snapshotStorage()).get(String(row.storage_path)),{headers:{'Content-Type':'application/json','Content-Disposition':'attachment; filename="source-snapshot.json"','Cache-Control':'no-store'}});}
 if(action==='recommendations'){const id=uuid.parse(request.nextUrl.searchParams.get('businessId'));const business=owned((await repo.list<BusinessRecord>('business_profiles',{id}))[0],actor);return NextResponse.json(recommend(business.questionnaire,await loadRegistry(await serverRepository(),isSandbox())));}
 if(action==='document-download')return await downloadDocument(actor,z.string().min(10).max(2000).parse(request.nextUrl.searchParams.get('token')));
 if(action==='calendar'){const rows=verifiedObligations(await repo.list('company_obligations'),await loadRegistry(await serverRepository(),isSandbox()));const{calendarIcs}=await import('../../../../../packages/compliance-engine');return new Response(calendarIcs(rows.map(o=>({id:String(o.id),code:String(o.obligation_code),title:String(o.title),periodStart:String(o.period_start),periodEnd:String(o.period_end),dueDate:o.due_at?new Date(String(o.due_at)).toISOString().slice(0,10):null,amountMinor:o.amount_minor===null?null:Number(o.amount_minor),currency:String(o.currency),status:o.status as 'pending'|'review_required',ruleVersionId:o.source_rule_version_id as string|null,evidence:[],notes:String(o.notes)}))),{headers:{'Content-Type':'text/calendar; charset=utf-8','Content-Disposition':'attachment; filename="cumplimiento.ics"','Cache-Control':'no-store'}});}
 throw new DomainError('NOT_FOUND','Ruta no encontrada',404);
 }catch(error){return errorResponse(error);}}
export async function POST(request:NextRequest,context:{params:Promise<{action:string[]}>}){try{const action=(await context.params).action.join('/');
 if(action==='stripe-webhook'){const raw=Buffer.from(await limitedBytes(request,262144)).toString('utf8');const signature=request.headers.get('stripe-signature');if(!signature||!process.env.STRIPE_SECRET_KEY||!process.env.STRIPE_WEBHOOK_SECRET)throw new DomainError('WEBHOOK_INVALID','Webhook no configurado o firma ausente',400);let event;try{event=verifyStripeEvent(raw,signature,process.env.STRIPE_SECRET_KEY,process.env.STRIPE_WEBHOOK_SECRET);}catch{throw new DomainError('WEBHOOK_INVALID','Firma o evento no válido',400);}if(event.type==='checkout.session.completed'||event.type==='checkout.session.async_payment_succeeded'){const session=event.data.object;if(session.mode==='payment'&&session.payment_status==='paid'&&session.metadata?.order_id)await(await application()).settleOrder(session.metadata.order_id,{mock:false,sessionId:session.id,amount:session.amount_total??undefined,currency:session.currency??undefined,eventId:event.id,eventHash:hashText(raw)});}await applySubscriptionEvent(await serverRepository(),event,hashText(raw),process.env.STRIPE_COMPLIANCE_PRICE_ID??'');return NextResponse.json({received:true});}
 sameOrigin(request);const service=await serverRepository();
 if(action==='oauth-google'){if(!await service.rateLimit('auth:google',30,60))throw new DomainError('RATE_LIMIT','Demasiados intentos. Espera un minuto.',429);const raw=Buffer.from(await limitedBytes(request,1024)).toString('utf8');z.object({}).strict().parse(raw?JSON.parse(raw):{});return NextResponse.json(await googleSignIn(),{headers:{'Cache-Control':'no-store'}});}
 if(['signup','login','sandbox-ops'].includes(action)){if(!await service.rateLimit(`auth:${action}`,30,60))throw new DomainError('RATE_LIMIT','Demasiados intentos. Espera un minuto.',429);const body=action==='sandbox-ops'?{}:JSON.parse(Buffer.from(await limitedBytes(request)).toString('utf8'));if(action==='signup')return NextResponse.json(await signup(body));if(action==='login'){await login(body);return NextResponse.json({ok:true});}await sandboxOps();return NextResponse.json({ok:true});}
 const actor=await requireActor();if(!await service.rateLimit(`actor:${actor.id}`,120,60))throw new DomainError('RATE_LIMIT','Demasiadas solicitudes; espera un minuto',429);
 if(action==='upload'){const bytes=await limitedBytes(request,11*1024*1024);const form=await new Response(bytes,{headers:{'Content-Type':request.headers.get('content-type')||''}}).formData();const file=form.get('file');if(!(file instanceof File))throw new DomainError('FILE_REQUIRED','Selecciona un archivo');return NextResponse.json(await uploadDocument(actor,uuid.parse(form.get('caseId')),file));}
 const raw=Buffer.from(await limitedBytes(request)).toString('utf8');const body=raw?JSON.parse(raw):{};const app=await application();
 if(action==='logout'){await logout();return NextResponse.json({ok:true});}
 if(action==='case-brief')return NextResponse.json(await prepareCaseBrief(service,actor,body),{headers:{'Cache-Control':'no-store'}});
 if(action==='agent-lab-evaluate')return NextResponse.json(await evaluateCaseGuide(service,actor,isSandbox(),body),{headers:{'Cache-Control':'no-store'}});
 if(action==='onboard'){const input=z.object({questionnaire:z.unknown(),founder:founderSchema}).parse(body);return NextResponse.json(await app.onboard(actor,input.questionnaire,{firstName:input.founder.legalFirstName,lastName:input.founder.legalLastName,dateOfBirth:input.founder.dateOfBirth}));}
 if(action==='case-create'){const input=z.object({businessId:uuid,jurisdiction:z.enum(JURISDICTIONS)}).parse(body);return NextResponse.json(await app.createCase(actor,input.businessId,input.jurisdiction));}
 if(action==='case-advance'){const input=z.object({caseId:uuid,stepCode:z.string().min(1).max(20),reference:z.string().max(300).optional(),confirmed:z.boolean(),mock:z.boolean().optional()}).parse(body);return NextResponse.json(await app.advance(actor,input.caseId,input));}
 if(action==='risk-review'){const input=z.object({caseId:uuid,reason:z.string().min(20).max(2000)}).parse(body);await app.approveRisk(actor,input.caseId,input.reason);return NextResponse.json({ok:true});}
 if(action==='checkout-create'){const{caseId}=z.object({caseId:uuid}).parse(body);const order=await app.prepareOrder(actor,caseId);const adapter=process.env.STRIPE_SECRET_KEY?new StripeTestCheckout(process.env.STRIPE_SECRET_KEY):isSandbox()?new SandboxCheckout():null;if(!adapter)throw new DomainError('EXTERNAL_BLOCKED','Stripe test requiere credenciales',503);const session=await adapter.create({orderId:String(order.id),organizationId:String(order.organization_id),caseId,amountMinor:Number(order.total_minor),currency:String(order.currency),origin:appOrigin(),idempotencyKey:String(order.idempotency_key)});await service.atomic([{kind:'update',table:'orders',where:{id:order.id},data:{stripe_checkout_session_id:session.sessionId}}]);return NextResponse.json({...session,mode:adapter.mode});}
 if(action==='checkout-mock'){const{orderId}=z.object({orderId:uuid}).parse(body);return NextResponse.json(await app.settleOrder(orderId,{mock:true},actor));}
 if(action==='subscription-create'){const{companyId}=z.object({companyId:uuid}).parse(body);if(!process.env.STRIPE_SECRET_KEY&&isSandbox())return NextResponse.json(await activateSandboxSubscription(service,actor,companyId,true));if(!process.env.STRIPE_SECRET_KEY||!process.env.STRIPE_COMPLIANCE_PRICE_ID)throw new DomainError('EXTERNAL_BLOCKED','Configura Stripe test y el precio anual autorizado',503);const sub=await prepareSubscription(service,actor,companyId);if(sub.status!=='pending')throw new DomainError('SUBSCRIPTION_STATE','La compañía ya tiene una suscripción en proceso o activa',409);return NextResponse.json(await new StripeTestCheckout(process.env.STRIPE_SECRET_KEY).subscription({subscriptionId:String(sub.id),organizationId:String(sub.organization_id),companyId,priceId:process.env.STRIPE_COMPLIANCE_PRICE_ID,origin:appOrigin(),idempotencyKey:`subscription:${sub.id}`}));}
 if(action==='document-link'){const{id}=z.object({id:uuid}).parse(body);return NextResponse.json(await signedDocument(actor,id));}
 if(action==='document-review'){const{id,approve}=z.object({id:uuid,approve:z.boolean()}).parse(body);await app.documentReview(actor,id,approve);return NextResponse.json({ok:true});}
 if(action==='document-prepare'){const{businessId,jurisdiction}=z.object({businessId:uuid,jurisdiction:z.enum(JURISDICTIONS)}).parse(body);const business=owned((await service.list<BusinessRecord>('business_profiles',{id:businessId}))[0],actor);return NextResponse.json(prepareFormationDocument(jurisdiction,business.questionnaire));}
 if(action==='regulatory-answer'){const input=z.object({question:z.string().trim().min(4).max(2000),jurisdiction:z.enum(JURISDICTIONS)}).parse(body);const registry=await loadRegistry(service,isSandbox());let answer=answerRegulatoryQuestion(input.question,input,registry);let modelStatus='deterministic';if(process.env.OPENAI_API_KEY&&process.env.OPENAI_MODEL){try{answer=await answerWithOpenAI(input.question,input.jurisdiction,registry,{key:process.env.OPENAI_API_KEY,model:process.env.OPENAI_MODEL});modelStatus='verified_tool';}catch{modelStatus='deterministic_fallback';}}if(answer.requires_human_review)await service.atomic([{kind:'insert',table:'case_escalations',data:{organization_id:actor.organizationId,escalation_type:'regulatory_answer',severity:'HIGH',reason:answer.facts.length?'Consulta requiere criterio profesional':'No hay evidencia activa y vigente para la consulta'}}]);return NextResponse.json({...answer,model_status:modelStatus});}
 if(action==='compliance-generate')return NextResponse.json(await regenerateCompliance(service,actor,body,isSandbox()));
 if(action==='notify'){const{today}=z.object({today:z.iso.date().optional()}).parse(body);if(today){assertCompliance(actor.role);if(!isSandbox())throw new DomainError('SIMULATION_DISABLED','No se admite simular fechas fuera del sandbox',403);}return NextResponse.json(await app.notifications(actor,today));}
 if(action==='support'){const input=z.object({subject:z.string().trim().min(3).max(200),message:z.string().trim().min(10).max(5000)}).parse(body);return NextResponse.json(await app.support(actor,input.subject,input.message));}
 if(action==='settings'){const input=z.object({displayName:z.string().trim().min(1).max(100),timezone:z.string().min(1).max(80)}).parse(body);try{new Intl.DateTimeFormat('es',{timeZone:input.timezone});}catch{throw new DomainError('TIMEZONE_INVALID','Zona horaria inválida');}if(isSandbox()){const{localDb}=await import('../../../lib/runtime');await(await localDb()).query('update profiles set display_name=$1,timezone=$2 where id=$3',[input.displayName,input.timezone,actor.id]);}else{const{error}=await(await supabaseAuth()).from('profiles').update({display_name:input.displayName,timezone:input.timezone}).eq('id',actor.id);if(error)throw new Error('Profile update failed');}return NextResponse.json({ok:true});}
 if(action==='source-monitor'||action==='source-ingest'){assertCompliance(actor.role);const{sourceId}=z.object({sourceId:uuid}).parse(body);const result=await monitorSource(service,actor,sourceId,await snapshotStorage());const{normalized,...safe}=result;void normalized;return NextResponse.json(safe);}
 if(action==='source-review'){const{sourceId,reason}=z.object({sourceId:uuid,reason:z.string().min(30).max(5000)}).parse(body);return NextResponse.json(await reviewSource(service,actor,sourceId,reason));}
 if(action==='rule-draft')return NextResponse.json(await createRuleDraft(service,actor,body));
 if(action==='rule-publish'){const{versionId,reason}=z.object({versionId:uuid,reason:z.string().min(30).max(5000)}).parse(body);return NextResponse.json(await publishCandidate(service,actor,versionId,reason,isSandbox()));}
 if(action==='escalation-resolve'){assertInternal(actor.role);const{id,resolution}=z.object({id:uuid,resolution:z.string().trim().min(20).max(5000)}).parse(body);await service.atomic([{kind:'update',table:'case_escalations',where:{id},data:{status:'resolved',resolution,assigned_to:actor.id,resolved_at:new Date().toISOString()}},{kind:'insert',table:'audit_logs',data:{actor_user_id:actor.id,action:'ESCALATION_RESOLVED',resource_type:'case_escalations',resource_id:id}}]);return NextResponse.json({ok:true});}
 throw new DomainError('NOT_FOUND','Ruta no encontrada',404);
 }catch(error){return errorResponse(error);}}
